// ABOUTME: Artifact integrity manifest (SPEC §4.5) — SHA-256 check of wasm+zkey on load, generated by
// ABOUTME: the armada-circuits build. Replaces the IPFS download + Railgun hash-whitelist + overrideArtifact.

import { sha256 } from '@noble/hashes/sha256';
import { ArtifactIntegrityError } from '../errors';
import type { ArtifactSet, ArtifactSource, CircuitShape } from './index';

/** SHA-256 (hex) of each artifact file for one circuit shape. `vkey` is optional — older manifests omit it. */
export interface ArtifactDigest {
  readonly wasm: string;
  readonly zkey: string;
  readonly vkey?: string;
}

/** Keyed by shape (`${nullifiers}x${commitments}`) — emitted by the armada-circuits build. */
export type ArtifactManifest = Readonly<Record<string, ArtifactDigest>>;

export function shapeKey(shape: CircuitShape): string {
  return `${shape.nullifiers}x${shape.commitments}`;
}

function sha256Hex(bytes: Uint8Array): string {
  const digest = sha256(bytes);
  let hex = '';
  for (const b of digest) hex += b.toString(16).padStart(2, '0');
  return hex;
}

/** SHA-256 digest of a resolved artifact set — the manifest entry the build emits for one shape. Includes
 *  the vkey digest when the set carries the raw vkey bytes. */
export function artifactDigest(artifacts: ArtifactSet): ArtifactDigest {
  return {
    wasm: sha256Hex(artifacts.wasm),
    zkey: sha256Hex(artifacts.zkey),
    ...(artifacts.vkeyRaw !== undefined ? { vkey: sha256Hex(artifacts.vkeyRaw) } : {}),
  };
}

/**
 * Verify an artifact set against the manifest for its shape. Throws `ArtifactIntegrityError` if the
 * shape is missing from the manifest or a wasm/zkey digest does not match.
 */
export function verifyArtifactIntegrity(
  shape: CircuitShape,
  artifacts: ArtifactSet,
  manifest: ArtifactManifest,
): void {
  const key = shapeKey(shape);
  const expected = manifest[key];
  if (expected === undefined) {
    throw new ArtifactIntegrityError(`no manifest entry for circuit shape ${key}`);
  }
  const wasm = sha256Hex(artifacts.wasm);
  if (wasm !== expected.wasm) {
    throw new ArtifactIntegrityError(`wasm digest mismatch for ${key}: expected ${expected.wasm}, got ${wasm}`);
  }
  const zkey = sha256Hex(artifacts.zkey);
  if (zkey !== expected.zkey) {
    throw new ArtifactIntegrityError(`zkey digest mismatch for ${key}: expected ${expected.zkey}, got ${zkey}`);
  }
  // Verify the vkey too when BOTH the manifest pins it and the source provided the raw bytes. A manifest
  // that pins a vkey digest but a source that can't supply `vkeyRaw` is a misconfiguration — reject it
  // rather than silently skipping (the whole point of pinning the vkey is that it's checked).
  if (expected.vkey !== undefined) {
    if (artifacts.vkeyRaw === undefined) {
      throw new ArtifactIntegrityError(`manifest pins a vkey digest for ${key} but the source provided no raw vkey bytes`);
    }
    const vkey = sha256Hex(artifacts.vkeyRaw);
    if (vkey !== expected.vkey) {
      throw new ArtifactIntegrityError(`vkey digest mismatch for ${key}: expected ${expected.vkey}, got ${vkey}`);
    }
  }
}

/** Wraps an ArtifactSource, verifying integrity against a manifest on every resolve. */
export class VerifiedArtifactSource implements ArtifactSource {
  constructor(
    private readonly inner: ArtifactSource,
    private readonly manifest: ArtifactManifest,
  ) {}

  async resolve(shape: CircuitShape): Promise<ArtifactSet> {
    const artifacts = await this.inner.resolve(shape);
    verifyArtifactIntegrity(shape, artifacts, this.manifest);
    return artifacts;
  }
}
