// ABOUTME: Artifact integrity manifest (SPEC §4.5) — SHA-256 check of wasm+zkey on load, generated by
// ABOUTME: the armada-circuits build. Replaces the IPFS download + Railgun hash-whitelist + overrideArtifact.

import { sha256 } from '@noble/hashes/sha256';
import { ArtifactIntegrityError } from '../errors';
import type { ArtifactSet, ArtifactSource, CircuitShape } from './index';

/** SHA-256 (hex) of each artifact file for one circuit shape. */
export interface ArtifactDigest {
  readonly wasm: string;
  readonly zkey: string;
}

/** Keyed by shape (`${nullifiers}x${commitments}`) — emitted by the armada-circuits build. */
export type ArtifactManifest = Readonly<Record<string, ArtifactDigest>>;

export function shapeKey(shape: CircuitShape): string {
  return `${shape.nullifiers}x${shape.commitments}`;
}

function sha256Hex(bytes: Uint8Array): string {
  const digest = sha256(bytes);
  let hex = '';
  for (const b of digest) hex += b.toString(16).padStart(2, '0');
  return hex;
}

/**
 * Verify an artifact set against the manifest for its shape. Throws `ArtifactIntegrityError` if the
 * shape is missing from the manifest or a wasm/zkey digest does not match.
 */
export function verifyArtifactIntegrity(
  shape: CircuitShape,
  artifacts: ArtifactSet,
  manifest: ArtifactManifest,
): void {
  const key = shapeKey(shape);
  const expected = manifest[key];
  if (expected === undefined) {
    throw new ArtifactIntegrityError(`no manifest entry for circuit shape ${key}`);
  }
  const wasm = sha256Hex(artifacts.wasm);
  if (wasm !== expected.wasm) {
    throw new ArtifactIntegrityError(`wasm digest mismatch for ${key}: expected ${expected.wasm}, got ${wasm}`);
  }
  const zkey = sha256Hex(artifacts.zkey);
  if (zkey !== expected.zkey) {
    throw new ArtifactIntegrityError(`zkey digest mismatch for ${key}: expected ${expected.zkey}, got ${zkey}`);
  }
}

/** Wraps an ArtifactSource, verifying integrity against a manifest on every resolve. */
export class VerifiedArtifactSource implements ArtifactSource {
  constructor(
    private readonly inner: ArtifactSource,
    private readonly manifest: ArtifactManifest,
  ) {}

  async resolve(shape: CircuitShape): Promise<ArtifactSet> {
    const artifacts = await this.inner.resolve(shape);
    verifyArtifactIntegrity(shape, artifacts, this.manifest);
    return artifacts;
  }
}
